{lib}: {
  inherit lib;

  debug = {
    inherit (builtins) tryEval;
    inherit (lib.asserts) assertMsg;
    inherit (lib.debug) addErrorContext traceIf;
    inherit (lib.trivial) deepSeq;
  };

  strings = {
    inherit
      (lib.strings)
      addContextFrom
      appendContext
      charToInt
      cmakeBool
      cmakeFeature
      cmakeOptionType
      commonPrefixLength
      commonSuffixLength
      compareVersions
      concatImapStrings
      concatImapStringsSep
      concatLines
      concatMapAttrsStringSep
      concatMapStrings
      concatMapStringsSep
      concatStrings
      concatStringsSep
      elem
      elemAt
      enableFeature
      enableFeatureAs
      escape
      escapeC
      escapeNixIdentifier
      escapeNixString
      escapeRegex
      escapeShellArg
      escapeShellArgs
      escapeURL
      escapeXML
      fileContents
      filter
      fixedWidthNumber
      fixedWidthString
      floatToString
      fromJSON
      genList
      getName
      getVersion
      hasInfix
      hasPrefix
      hasSuffix
      head
      intersperse
      isAttrs
      isConvertibleWithToString
      isInt
      isList
      isPath
      isStorePath
      isString
      isStringLike
      isValidPosixName
      join
      levenshtein
      levenshteinAtMost
      lowerChars
      makeBinPath
      makeIncludePath
      makeLibraryPath
      makeSearchPath
      makeSearchPathOutput
      match
      mesonBool
      mesonEnable
      mesonOption
      nameFromURL
      normalizePath
      optionalString
      parseDrvName
      readFile
      removePrefix
      removeSuffix
      replaceString
      replaceStrings
      replicate
      sanitizeDerivationName
      split
      splitString
      splitStringBy
      storeDir
      stringAsChars
      stringLength
      stringToCharacters
      substring
      tail
      toCamelCase
      toInt
      toIntBase10
      toJSON
      toLower
      toSentenceCase
      toShellVar
      toShellVars
      toUpper
      trim
      trimWith
      typeOf
      unsafeDiscardStringContext
      upperChars
      versionAtLeast
      versionOlder
      withFeature
      withFeatureAs
      ;
  };

  system = {
    inherit (lib) nixosSystem darwinSystem;
  };

  types = {
    inherit (lib.trivial) isBool isFloat isFunction;
    inherit
      (lib.strings)
      isAttrs
      isConvertibleWithToString
      isInt
      isList
      isPath
      isStorePath
      isString
      isStringLike
      isValidPosixName
      typeOf
      ;
    inherit
      (lib.types)
      addCheck
      anything
      attrs
      attrsOf
      attrsWith
      attrTag
      bool
      boolByOr
      coercedTo
      commas
      defaultFunctor
      defaultTypeMerge
      deferredModule
      deferredModuleWith
      either
      enum
      envVar
      externalPath
      fileset
      float
      functionTo
      int
      ints
      isOptionType
      isType
      json
      lazyAttrsOf
      lines
      listOf
      loaOf
      luaInline
      mergeTypes
      mkOptionType
      noCheckForDocsModule
      nonEmptyListOf
      nonEmptyStr
      nullOr
      number
      numbers
      oneOf
      optionDeclaration
      optionDescriptionPhrase
      optionType
      package
      passwdEntry
      path
      pathInStore
      pathWith
      pkgs
      port
      raw
      separatedString
      serializableValueWith
      setType
      shellPackage
      singleLineStr
      str
      strMatching
      submodule
      submoduleWith
      toml
      uniq
      unique
      unspecified
      ;
  };
}
